version: '3.8'

services:
  beribturing-admin:
    image: frontend-beribturing-admin
    container_name: beribturing-admin
    build:
      context: .
      dockerfile: front-dev.dockerfile
      args:
        APP_NAME: admin-app
        PACKAGE_NAME: "@beribturing/admin-app"
    ports:
      - "3001:3000"
    networks:
      - beribturing-network

  beribturing-owner:
    image: frontend-beribturing-owner
    container_name: beribturing-owner
    build:
      context: .
      dockerfile: front-dev.dockerfile
      args:
        APP_NAME: owner-app
        PACKAGE_NAME: "@beribturing/owner-app"
    ports:
      - "3002:3000"
    networks:
      - beribturing-network

  beribturing-renter:
    image: frontend-beribturing-renter
    container_name: beribturing-renter
    build:
      context: .
      dockerfile: front-dev.dockerfile
      args:
        APP_NAME: renter-app
        PACKAGE_NAME: "@beribturing/rental-app"
    ports:
      - "3003:3000"
    networks:
      - beribturing-network

  nginx:
    image: nginx:alpine
    container_name: beribturing-nginx
    ports:
      - "80:80"
    volumes:
      - ./.nginx/proxy.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - beribturing-admin
      - beribturing-owner
      - beribturing-renter
    networks:
      - beribturing-network

networks:
  beribturing-network:
    driver: bridge
