version: '3.8'

services:
  beribturing-admin:
    container_name: beribturing-admin
    build:
      context: .
      dockerfile: front-dev.dockerfile
      args:
        APP_NAME: admin-app
        PACKAGE_NAME: "@beribturing/admin-app"
    expose:
      - "3000"

  beribturing-owner:
    container_name: beribturing-owner
    build:
      context: .
      dockerfile: front-dev.dockerfile
      args:
        APP_NAME: owner-app
        PACKAGE_NAME: "@beribturing/owner-app"
    expose:
      - "3000"

  beribturing-renter:
    container_name: beribturing-renter
    build:
      context: .
      dockerfile: front-dev.dockerfile
      args:
        APP_NAME: renter-app
        PACKAGE_NAME: "@beribturing/rental-app"
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: beribturing-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - beribturing-admin
      - beribturing-owner
      - beribturing-renter
    links:
      - beribturing-admin
      - beribturing-owner
      - beribturing-renter
