export enum NotificationType {
  RENTAL_REQUEST = 'RENTAL_REQUEST',
  RENTAL_APPROVED = 'RENTAL_APPROVED',
  RENTAL_REJECTED = 'RENTAL_REJECTED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  MAINTENANCE_SCHEDULED = 'MAINTENANCE_SCHEDULED',
  MAINTENANCE_COMPLETED = 'MAINTENANCE_COMPLETED',
  SYSTEM_ALERT = 'SYSTEM_ALERT'
} 