export enum ActivityType {
  //
  ITEM_VIEWED,
  ITEM_LISTED,
  BOOKING_CREATED,
  BOOKING_CANCELLED,
  ITEM_UPDATED,
  SYSTEM_ACTION,
  MESSAGE_SENT,
  PAYMENT_SENT,
  PAYMENT_CANCELLED,
  NOTIFICATION_RECEIVED
}
